planckton/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('timetracker.urls', namespace="timetracker")),
    url(r'^admin/', include(admin.site.urls)),
]

timetracker/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^employer/create/', views.create_employer, name='create_employer'),
    url(r'^employer/edit/(?P<employer_id>[0-9]+)/', views.edit_employer, name='edit_employer'),
    url(r'^project/create/(?P<employer_id>[0-9]+)/', views.create_project, name='create_project'),
    url(r'^project/edit/(?P<project_id>[0-9]+)/', views.edit_project, name='edit_project'),
    url(r'^project/show/(?P<project_id>[0-9]+)/', views.show_project, name='show_project'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^api/', views.api, name='api'),
]

timetracker/models.py
from django.contrib.auth.models import User
from django.db import models

class Employer(models.Model):
    """
    The employer you work for (e.g. 'Planckton IT Solutions').
    Each project belongs to exactly one employer.

    The default_hourly_wage is only used when there is no default_hourly_wage
    set for the corresponding Project and the Timeframe.
    """
    user = models.ForeignKey(User)
    name = models.CharField('Name', max_length=200)
    default_hourly_wage = models.DecimalField('Default hourly wage', max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

class Project(models.Model):
    """
    A project might be something like 'Website for company X'.
    Each project also contains some meta-data such as the name of the client
    who pays your employer (who (hopefully) then pays you).
    """
    user = models.ForeignKey(User)
    employer = models.ForeignKey(Employer)
    name = models.CharField('Project name', max_length=200)
    client_name = models.CharField('Client name', max_length=200, blank=True)
    notes = models.TextField('Notes', max_length=2000, blank=True)
    default_hourly_wage = models.DecimalField('Default hourly wage', max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

class Timeframe(models.Model):
    """
    A timeframe is the time you spend working on a project without interuption.
    The might be many timeframes for a single project.
    """
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    hourly_wage = models.DecimalField('Hourly wage', max_digits=5, decimal_places=2)
    datetime_start = models.DateTimeField('Start date and time')
    datetime_end = models.DateTimeField('End date and time')
    summary = models.CharField('Summary', max_length=2000)

class ActiveTimer(models.Model):
    """
    An active timeframe is a timer which has not been stopped yet. There should
    be one timer per user and project at most.
    """
    STATE_CHOICES = (
        (0, 'TIMER_NOT_RUNNING'),
        (1, 'TIMER_RUNNING'),
        (2, 'TIMER_UNSAVED'),
    )
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project, primary_key=True)
    state = models.PositiveSmallIntegerField(choices=STATE_CHOICES)
    hourly_wage = models.DecimalField('Hourly wage', max_digits=5, decimal_places=2)
    datetime_start = models.DateTimeField('Start date and time')
    datetime_end = models.DateTimeField('End date and time')
    summary = models.CharField('Summary', max_length=2000)

timetracker/forms.py
from django import forms
from django.forms import ModelForm

from .models import Employer, Project, Timeframe, ActiveTimer

class BootstrapModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class EmployerForm(BootstrapModelForm):
    class Meta:
        model = Employer
        fields = ['name', 'default_hourly_wage']

class ProjectForm(BootstrapModelForm):
    class Meta:
        model = Project
        fields = ['employer', 'name', 'client_name', 'notes', 'default_hourly_wage']

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['employer'].queryset = Employer.objects.filter(user=self.instance.user)

class ActiveTimerForm(ModelForm):
    class Meta:
        model = ActiveTimer
        fields = ['project', 'state', 'hourly_wage', 'datetime_start', 'datetime_end', 'summary']

class TimeframeForm(ModelForm):
    class Meta:
        model = Timeframe
        fields = ['hourly_wage', 'datetime_start', 'datetime_end', 'summary']

class DeleteForm(forms.Form):
    id = forms.IntegerField()

timetracker/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect

from .forms import EmployerForm, ProjectForm, TimeframeForm, ActiveTimerForm, DeleteForm
from .models import Employer, Project, Timeframe, ActiveTimer


def logout_view(request):
    logout(request)
    return redirect('/')


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'timetracker/index_nologin.html', {})

    if request.method == "POST":
        if request.POST.get('action', '') == 'delete_employer':
            delete_form = DeleteForm(request.POST)
            if delete_form.is_valid():
                employer = get_object_or_404(Employer, pk=delete_form.cleaned_data['id'], user=request.user)
                employer.delete()

        elif request.POST.get('action', '') == 'delete_project':
            delete_form = DeleteForm(request.POST)
            if delete_form.is_valid():
                project = get_object_or_404(Project, pk=delete_form.cleaned_data['id'], user=request.user)
                project.delete()

    return render(request, 'timetracker/index.html', {
        'employer_set': Employer.objects.filter(user=request.user)
    })


def api(request):
    if not request.user.is_authenticated():
        return JsonResponse({'error': 'login_required'}, status=403)

    if request.method == "POST":
        if request.POST.get('action', '') == 'set_timer_status':
            # start a new timer
            try:
                project = Project.objects.get(pk=request.POST.get('project', -1), user=request.user)
            except ObjectDoesNotExist:
                return JsonResponse({'error': 'project_does_not_exist'})

            try:
                timer = ActiveTimer.objects.get(user=request.user, project=project)
            except ObjectDoesNotExist:
                timer = ActiveTimer(user=request.user, project=project)

            active_timer_form = ActiveTimerForm(request.POST, instance=timer)

            if active_timer_form.is_valid():
                active_timer_form.save()
            else:
                return JsonResponse({'error': 'invalid_data'}, status=200)

            return JsonResponse({'success': True}, status=200)

        if request.POST.get('action', '') == 'get_timer_status':
            # return the status of the timer for a given project
            try:
                timer = ActiveTimer.objects.get(user=request.user, project=request.POST.get('project', -1))
            except ObjectDoesNotExist:
                return JsonResponse({'error': 'timer_does_not_exist'})

            return JsonResponse({
                'success': True,
                'state': timer.state,
                'hourly_wage': timer.hourly_wage,
                'datetime_start': timer.datetime_start,
                'datetime_end': timer.datetime_end,
                'summary': timer.summary,
            }, status=200)

        elif request.POST.get('action', '') == 'change_timeframe':
            # TODO update a previous timeframe
            return JsonResponse({'error': 'unknown_request'}, status=501)

    return JsonResponse({'error': 'unknown_request'}, status=501)


@login_required
def create_employer(request):
    if request.method == "POST":
        new_employer = Employer(user=request.user)
        create_employer_form = EmployerForm(request.POST, instance=new_employer)
        if create_employer_form.is_valid():
            create_employer_form.save()
            return HttpResponseRedirect(reverse('timetracker:index'))
    else:
        create_employer_form = EmployerForm()

    return render(request, 'timetracker/create_employer.html', {
        'form': create_employer_form,
    })


@login_required
def edit_employer(request, employer_id):
    employer = get_object_or_404(Employer, pk=employer_id, user=request.user)

    if request.method == "POST":
        edit_employer_form = EmployerForm(request.POST, instance=employer)
        if edit_employer_form.is_valid():
            edit_employer_form.save()
            return HttpResponseRedirect(reverse('timetracker:index'))
    else:
        edit_employer_form = EmployerForm(instance=employer)

    return render(request, 'timetracker/edit_employer.html', {
        'form': edit_employer_form,
    })


@login_required
def create_project(request, employer_id):
    if request.method == "POST":
        new_project = Project(user=request.user)
        create_project_form = ProjectForm(request.POST, instance=new_project)
        if create_project_form.is_valid():
            create_project_form.save()
            return HttpResponseRedirect(reverse('timetracker:index'))
    else:
        employer = get_object_or_404(Employer, pk=employer_id, user=request.user)
        new_project = Project(employer=employer, user=request.user, default_hourly_wage=employer.default_hourly_wage)
        create_project_form = ProjectForm(instance=new_project)

    return render(request, 'timetracker/create_project.html', {
        'form': create_project_form,
    })


@login_required
def edit_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id, user=request.user)

    if request.method == "POST":
        edit_project_form = ProjectForm(request.POST, instance=project)
        if edit_project_form.is_valid():
                edit_project_form.save()
                return HttpResponseRedirect(reverse('timetracker:index'))
    else:
        edit_project_form = ProjectForm(instance=project)

    return render(request, 'timetracker/edit_project.html', {
        'form': edit_project_form,
    })


@login_required
def show_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id, user=request.user)

    if request.method == "POST":
        if request.POST.get('action', '') == 'add_timeframe':
            new_timeframe = Timeframe(user=request.user, project=project)
            add_form = TimeframeForm(request.POST, instance=new_timeframe)
            if add_form.is_valid():
                add_form.save()
                ActiveTimer.objects.filter(user=request.user, project=project).delete()


        if request.POST.get('action', '') == 'delete_timeframe':
            delete_form = DeleteForm(request.POST)
            if delete_form.is_valid():
                timeframe = get_object_or_404(Timeframe, pk=delete_form.cleaned_data['id'], user=request.user)
                timeframe.delete()

    return render(request, 'timetracker/show_project.html', {
        'project': project,
        'timeframe_set': Timeframe.objects.filter(user=request.user, project=project),
        'employer_set': Employer.objects.filter(user=request.user),
    })

timetracker/templates/timetracker/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="icon" type="image/png" href="{% static 'timetracker/favicon_128.png' %}" />
    <title>{% block title %}{% endblock %} - Planckton</title>
    <link href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css' %}" rel="stylesheet">
    <link href="{% static 'timetracker/style.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        {% if not user.is_authenticated %}
        <a class="btn btn-default navbar-btn navbar-right pull-right" href="{% url 'timetracker:login' %}" role="button"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login</a>
        {% endif %}

        <div class="navbar-header">
          {% if user.is_authenticated %}
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% endif %}
          <a class="navbar-brand" href="/">
            <img alt="Brand" src="{% static 'timetracker/favicon_128.png' %}">
          </a>
          <a class="navbar-brand" href="/">Planckton</a>
        </div>

        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbar-top-collapse-1">
          {% if employer_set %}
          <ul class="nav navbar-nav">
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects <span class="caret"></span></a>
              <ul class="dropdown-menu">
                {% for employer in employer_set %}
                {% for project in employer.project_set.all %}
                <li><a href="{% url 'timetracker:show_project' project.id %}">{{project.name}}</a></li>
                {% endfor %}
                {% if employer.project_set.count != 0 %}
                <li role="separator" class="divider"></li>
                {% endif %}
                {% endfor %}
                <li><a href="{% url 'timetracker:index' %}"><em>Manage projects</em></a></li>
              </ul>
            </li>
          </ul>
          {% endif %}

          <a class="btn btn-default navbar-btn navbar-right" href="{% url 'timetracker:logout' %}" role="button"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout</a>
          <p class="navbar-text navbar-right" style="margin-right: 1em;">Signed in as <em>{{ user.username }}</em></p>
        </div>
        {% endif %}
      </div>
    </nav>

    {% block content %}{% endblock %}

    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'timetracker/app.js' %}"></script>
  </body>
</html>

timetracker/templates/timetracker/content_single_form.html
{% extends "timetracker/base.html" %}

{% block content %}
  <div class="container">

    {% if error_message %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Error!</strong> {{ error_message }}
      </div>
    {% endif %}

    {% block description %}{% endblock %}

    <div class="panel panel-default col-lg-6 col-md-8 col-sm-10 col-xs-12">
      <div class="panel-body">
        <form action="" method="post" class="form-horizontal">
          {% csrf_token %}
          {% include "timetracker/form_snippet.html" with form=form submit_text="Save" %}
        </form>
      </div>
    </div>

  </div>
{% endblock %}

timetracker/templates/timetracker/createProject.html
{% extends "timetracker/base.html" %}

{% block title %}Create a new project{% endblock %}

{% block content %}
  <div class="container">
    {% if error_message %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Error!</strong> {{ error_message }}
      </div>
    {% endif %}

    <ol class="breadcrumb">
      <li><a href="{% url 'timetracker:index' %}">Projects</a></li>
      <li><a href="">Create a new project</a></li>
    </ol>

    <div class="page-header">
      <h1>Create a new project <small></small></h1>
    </div>

    <p>A project might be something like 'Website for company X'.</p>
    <p class="margin-bottom">
      Each project also contains some meta-data such as the name of the client
      who pays your employer (who (hopefully) then pays you).</p>

    <div class="panel panel-default maxwidth50">
      <div class="panel-body">
        <form action="" method="post" class="form-horizontal">
          {% csrf_token %}
          {% include "timetracker/form_snippet.html" with form=create_project_form submit_text="Create" %}
        </form>
      </div>
    </div>

  </div>
{% endblock %}

timetracker/templates/timetracker/create_employer.html
{% extends "timetracker/content_single_form.html" %}

{% block description %}
  <div class="page-header">
    <h1>{% block title %}Create a new employer{% endblock %}</h1>
  </div>

  <p>An employer is someone you work for (e.g. 'Planckton IT Solutions').</p>
  <p class="margin-bottom2">Each project belongs to exactly one employer.</p>
{% endblock %}

timetracker/templates/timetracker/create_project.html
{% extends "timetracker/content_single_form.html" %}

{% block description %}
  <div class="page-header">
    <h1>{% block title %}Create a new project{% endblock %}</h1>
  </div>

  <p>A project might be something like 'Website for company X'.</p>
  <p class="margin-bottom2">
    Each project also contains some meta-data such as the name of the client
    who pays your employer (who (hopefully) then pays you).</p>
{% endblock %}

timetracker/templates/timetracker/edit_employer.html
{% extends "timetracker/content_single_form.html" %}

{% block description %}
  <div class="page-header">
    <h1>{% block title %}Edit existing employer{% endblock %}</h1>
  </div>

  <p>You are editing: {{ employer_name }}</p>
{% endblock %}

timetracker/templates/timetracker/edit_project.html
{% extends "timetracker/content_single_form.html" %}

{% block description %}
  <div class="page-header">
    <h1>{% block title %}Edit existing project{% endblock %}</h1>
  </div>

  <p>You are editing: {{ project_name }}</p>
{% endblock %}

timetracker/templates/timetracker/form_snippet.html
{% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert"><strong>Error!</strong> {{ error|escape }}</div>
  {% endfor %}
{% endif %}
{% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}" class="col-sm-4 control-label">{{ field.label }}</label>
    <div class="col-sm-8">
      {% if field.name == 'default_hourly_wage' or field.name == 'hourly_wage' %}
        <div class="input-group">
          {{ field }}
          <div class="input-group-addon">&euro;/&#36;/&pound;</div>
        </div>
      {% else %}
        {{ field }}
      {% endif %}
    </div>
  </div>
  <div class="col-sm-offset-4 col-sm-8">
    {% if field.errors %}
        {% for error in field.errors %}
          <div class="alert alert-danger margin-bottom2" role="alert"><strong>Error!</strong> {{ error|escape }}</div>
        {% endfor %}
    {% endif %}
  </div>
{% endfor %}
<div class="form-group">
  <div class="col-sm-offset-4 col-sm-8">
    {% if submit_text %}
      <input type="submit" class="btn btn-default" value="{{ submit_text }}">
    {% else %}
      <input type="submit" class="btn btn-default" value="Send">
    {% endif %}
  </div>
</div>

timetracker/templates/timetracker/index.html
{% extends "timetracker/base.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
  <div class="container">

    {% if error_message %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Error!</strong> {{ error_message }}
      </div>
    {% endif %}

    <div class="page-header">
      <h1>Projects <small></small></h1>
    </div>

    <a class="btn btn-default margin-bottom1" href="{% url 'timetracker:create_employer' %}" role="button"><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span> Create a new employer</a>

    {% if employer_set %}
      {% for employer in employer_set %}
      <a name="employer{{ employer.id }}"></a>

      <table class="table table-striped table-fixed-width table-hover margin-top2">
        <thead>
          <tr>
            <th colspan="2">{{ employer.name }}</th>
            <th>
              <div class="pull-right nowrap">
                <a href="{% url 'timetracker:edit_employer' employer.id %}" type="button" class="btn btn-default btn-sm" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit</a>
                <button type="button" data-toggle="modal" data-target="#deleteEmployerModal" onclick="$('#deleteEmployerId').val('{{ employer.id }}');" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete</button>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
        {% for project in employer.project_set.all %}
          <tr data-href="{% url 'timetracker:show_project' project.id %}">
            <td>{{project.name}}</td>
            <td>{{project.client_name}}</td>
            <td class="no-td-click">
              <div class="pull-right nowrap">
                <a href="{% url 'timetracker:edit_project' project.id %}" type="button" class="btn btn-default btn-sm" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit</a>
                <button type="button" data-toggle="modal" data-target="#deleteProjectModal" onclick="$('#deleteProjectId').val('{{ project.id }}');" class="btn btn-default btn-sm margin-right1"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete</button>
              </div>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <a class="btn btn-default btn-sm" href="{% url 'timetracker:create_project' employer.id %}" role="button"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Create a new project</a>
      {% endfor %}
    {% else %}
      <p class="margin-top2">No projects and employers are available.</p>
    {% endif %}

  </div>

  <!-- delete employer Modal -->
  <div class="modal fade" id="deleteEmployerModal" tabindex="-1" role="dialog" aria-labelledby="deleteEmployerModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="deleteEmployerModalLabel">Delete employer?</h4>
        </div>
        <div class="modal-body">
          Do you really want to delete this employer and all corresponding projects?
        </div>
        <div class="modal-footer">
          <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="action" value="delete_employer">
            <input type="hidden" name="id" value="" id="deleteEmployerId">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- delete project Modal -->
  <div class="modal fade" id="deleteProjectModal" tabindex="-1" role="dialog" aria-labelledby="deleteProjectModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="deleteProjectModalLabel">Delete Project?</h4>
        </div>
        <div class="modal-body">
          Do you really want to delete this project?
        </div>
        <div class="modal-footer">
          <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="action" value="delete_project">
            <input type="hidden" name="id" value="" id="deleteProjectId">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

timetracker/templates/timetracker/index_nologin.html
{% extends "timetracker/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="container-fluid plancton-container">
    <div class="container">
      <h1 class="margin-top1 margin-bottom1">Welcome to Planckton!</h1>
      <p>Planckton stands for <strong>Planck</strong>ton <strong>t</strong>ime
        <strong>on</strong>line and aims to be a powerful and easy-to-use time
        tracking software.</p>

      <h3>Is Planckton the right time tracking software for me?</h3>
      <div class="row">
        <p class="col-md-6">As plankton cannot swim against the current,
          Planckton is the right time tracking software for you because you
          probably cannot go back in time. If you can, this statement needs to
          be revised. Please file a bug in the bug tracker in this case!</p>
      </div>

      <a class="btn btn-default margin-top1 margin-bottom3" href="{% url 'timetracker:login' %}" role="button">
        Login</a>

      <p class="margin-top1 margin-bottom1">
        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        <a href="{% url 'timetracker:login' %}#TODO-registration" style="color: white;">
          Start time tracking today!
        </a>
      </p>

    </div>
  </div>

  <div class="container margin-top2 glyphicon-presenter">
    <div class="row margin-top2 margin-bottom2">
      <div class="col-md-6 col-sm-8 col-md-offset-1 margin-top1">
        <h2>Free Software</h2>
        <p>Planckton is free and open-source software. This means you have the
           right to <em>run the software however you would like</em>, <em> see
           how the software actually works</em>, <em>redistribute the software
           however you’d like</em> and you also have the right to <em>improve
           the program</em>. Check out the source code on
           <a href="https://github.com/codedust/planckton">github</a>.</p>
      </div>
      <div class="col-md-2 col-sm-2 hidden-xs glyphicon-wrapper glyphicon-wrapper-right">
        <span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>
      </div>
    </div>
    <div class="row margin-bottom2">
      <div class="col-md-2 col-sm-3 hidden-xs col-md-offset-1 glyphicon-wrapper glyphicon-wrapper-left">
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
      </div>
      <div class="col-md-6 col-sm-8">
        <h2>Time tracking made easy</h2>
        <p>Track your time using the built-in timer or just enter your own times.
           Planckton will do the rest.</p>
        <p><a href="{% url 'timetracker:index' %}#TODO-about">Tell me more!</a></p>
      </div>
    </div>
    <div class="row margin-bottom2">
      <div class="col-md-6 col-sm-8 col-md-offset-1 margin-top1">
        <h2>Accessible from your phone!</h2>
        <p>
          Planckton comes with support for small screens. No matter whether you
          are working at home, in your office or on the go, Planckton is only
          one fingertip away.</p>
      </div>
      <div class="col-md-2 col-sm-2 hidden-xs glyphicon-wrapper glyphicon-wrapper-right">
        <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
      </div>
    </div>

  </div>
{% endblock %}